---
  - name: restart samba
    ansible.builtin.service:
      name: "{{ item }}"
      state: restarted
    loop: [smbd, nmbd]

  - name: restart rsyslog
    ansible.builtin.service:
      name: rsyslog
      state: restarted
